apiVersion: ssp.kubevirt.io/v1beta2
kind: SSP
metadata:
  annotations:
    ssp.kubevirt.io/vm-console-proxy-enabled: "true"
    ssp.kubevirt.io/vm-console-proxy-namespace: "kubevirt"
  name: ssp-sample
  namespace: kubevirt
spec:
  commonTemplates:
    namespace: kubevirt
  templateValidator:
    replicas: 2
  featureGates:
    deployTektonTaskResources: true
  tektonPipelines:
    namespace: kubevirt
  tektonTasks:
    namespace: kubevirt
